### ISSUE TITLE
How to generate grasp labels

### ISSUE THREAD

**Issue by lishiyu005** [THU-VCLab/HGGD#3]
Dear author,

I want to train HGGD for another dataset. I want to know how to generate grasp labels from Graspnet-1billion dataset. Would you like to share your code for grasp generation?

Thank you very much.

Best regards,
Shiyu

**Comment by ChenThree** [comment]
Thanks for your interest in our work! Our data generation pipeline mainly follows the 6-Dof grasp to rect grasp conversion provided in the graspnet dataset api, while the difference is that we save the grasp rotation as Euler angels in the rect grasp class. There may not be an exact schedule for the code release for grasp generation, because it requires extra code reorganization and testing, but if there is any progress in the release of this part, we will update in this repo.

**Comment by lishiyu005** [comment]
Thanks for your answer. In my opinion, the current public available dataset for robotic grasping is in different format, which makes the cross training and validation difficult. Therefore it would be great that a unified format can be defined. Thanks for your contribution to publish this repo anyway.
